/**
 * Amplify client-side configuration.
 * Import this module once at the top of the component tree (RootLayout).
 */
import { Amplify } from 'aws-amplify';

// amplify_outputs.json is generated by `npx ampx sandbox` (local dev)
// or by the Amplify CI/CD pipeline (production).
// It is git-ignored and must never be committed.
let configured = false;

export async function configureAmplify() {
  if (configured) return;
  try {
    const outputs = await import('@/amplify_outputs.json');
    Amplify.configure(outputs.default, { ssr: true });
    configured = true;
  } catch {
    // amplify_outputs.json not yet generated (pre-sandbox). Silently skip.
    console.warn(
      '[Amplify] amplify_outputs.json not found. Run `npx ampx sandbox` to generate it.'
    );
  }
}
