import { a, defineData, type ClientSchema } from '@aws-amplify/backend';

/**
 * Data schema for Klug Kid Stories.
 *
 * Core design decisions:
 * - WordMeaning is the atomic unit: one row per distinct semantic sense of a lemma.
 * - UserWordProgress links a user to a word meaning and holds the SRS scheduling state.
 * - ReviewEvent is the immutable audit log used to refine the forgetting curve.
 * - Story is a generated review artefact; it is ephemeral and not queried historically.
 */
const schema = a.schema({
  // ─── Vocabulary ────────────────────────────────────────────────────────────

  WordMeaning: a
    .model({
      /** Lemma (base form, no inflection). e.g. "run", "être", "correr" */
      lemma: a.string().required(),
      /** Human-readable definition in the student's source language */
      meaning: a.string().required(),
      /** ISO 639-1 code of the language being learned. e.g. "de", "fr" */
      targetLanguage: a.string().required(),
      /** ISO 639-1 code of the student's native/reference language. e.g. "en" */
      sourceLanguage: a.string().required(),
      /** Optional example sentence in the target language */
      exampleSentence: a.string(),
      /**
       * When true this word meaning can appear in stories and progress data
       * of other users (used for pre-loaded frequency vocabulary).
       */
      isShared: a.boolean(),
      /**
       * Frequency rank within the target language corpus (1 = most frequent).
       * Only set for pre-loaded words; null for manually added words.
       */
      frequencyRank: a.integer(),
      /**
       * Origin of the word meaning entry.
       * 'preloaded'    – seeded from a frequency corpus, shared across all users.
       * 'manual'       – added manually by the student.
       * 'text_import'  – extracted from a student-pasted text.
       */
      sourceType: a.enum(['preloaded', 'manual', 'text_import']),
      userProgress: a.hasMany('UserWordProgress', 'wordMeaningId'),
      reviewEvents: a.hasMany('ReviewEvent', 'wordMeaningId'),
    })
    .authorization((allow) => [
      allow.owner(),
      allow.authenticated().to(['read']),
      allow.publicApiKey().to(['create', 'read', 'update', 'delete']),
    ]),

  // ─── SRS Progress ──────────────────────────────────────────────────────────

  UserWordProgress: a
    .model({
      wordMeaningId: a.id().required(),
      wordMeaning: a.belongsTo('WordMeaning', 'wordMeaningId'),
      /**
       * Estimated retention in days: value in [0, ∞).
       * Computed by the proprietary SRS algorithm after each review event.
       */
      retentionScore: a.integer(),
      /** Timestamp when the scheduler will surface this word for review again */
      nextReviewAt: a.datetime().required(),
      lastReviewedAt: a.datetime(),
      reviewCount: a.integer(),
      correctCount: a.integer(),
      /**
       * Timestamp when this word was first introduced to the student.
       * Set once at UserWordProgress creation; never mutated.
       * Used to enforce the maxNewWordsPerDay limit in the user's local timezone.
       */
      introducedAt: a.datetime().required(),
    })
    .authorization((allow) => [allow.owner()]),

  // ─── Review History ────────────────────────────────────────────────────────

  ReviewEvent: a
    .model({
      wordMeaningId: a.id().required(),
      wordMeaning: a.belongsTo('WordMeaning', 'wordMeaningId'),
      wasCorrect: a.boolean().required(),
      /** Raw similarity score from evaluateAnswer(): [0.0, 1.0] */
      responseScore: a.float(),
      /** Time the student took to answer, in milliseconds */
      responseTimeMs: a.integer(),
      /**
       * The story snippet presented to the student (for audit/ML use).
       * Stored as plain text with the blank represented as "___".
       */
      storyContext: a.string(),
    })
    .authorization((allow) => [allow.owner()]),

  // ─── Stories ───────────────────────────────────────────────────────────────

  Story: a
    .model({
      /** Full story text. Blanks are represented as "___". */
      content: a.string().required(),
      /** IDs of the word meanings being tested in this story */
      targetWordMeaningIds: a.string().array().required(),
      /** Language of the story */
      targetLanguage: a.string().required(),
    })
    .authorization((allow) => [allow.owner()]),

  // ─── Profile Topics ────────────────────────────────────────────────────────

  ProfileTopics: a
    .model({
      /**
       * 20 story-topic strings generated by Claude for this user's profile.
       * One record per user; regenerated when the profile snapshot changes.
       */
      topics: a.string().array().required(),
      /**
       * JSON snapshot of { age, gender, interests } at generation time.
       * Used to detect staleness when the profile is updated.
       */
      profileSnapshot: a.string().required(),
    })
    .authorization((allow) => [allow.owner()]),

  // ─── User Settings ─────────────────────────────────────────────────────────

  UserSettings: a
    .model({
      /** ISO 639-1 code of the language being learned. e.g. "de", "fr" */
      targetLanguage: a.string(),
      /** ISO 639-1 code of the student's native/reference language. e.g. "en" */
      sourceLanguage: a.string(),
      /** Maximum new word meanings introduced per calendar day (default: 10) */
      maxNewWordsPerDay: a.integer(),
      /** Maximum review items surfaced per calendar day (default: 100) */
      maxReviewsPerDay: a.integer(),
      /** Student's date of birth (ISO 8601 date, e.g. "2010-05-23") — age is computed at runtime */
      profileDateOfBirth: a.string(),
      /** Student's gender — used to personalise story characters (e.g. "male", "female", "other") */
      profileGender: a.string(),
      /** Comma-separated list of interests — used to choose story themes */
      profileInterests: a.string(),
    })
    .authorization((allow) => [allow.owner()]),
});

export type Schema = ClientSchema<typeof schema>;

export const data = defineData({
  schema,
  authorizationModes: {
    defaultAuthorizationMode: 'userPool',
    apiKeyAuthorizationMode: {
      expiresInDays: 365,
    },
  },
});
