'use client';

import { useEffect, useState } from 'react';
import { Amplify } from 'aws-amplify';
import { fetchAuthSession } from 'aws-amplify/auth';
import { Authenticator } from '@aws-amplify/ui-react';
import '@aws-amplify/ui-react/styles.css';

/**
 * Configures Amplify and provides the Authenticator context to the entire app.
 * Must be a Client Component because Amplify.configure() and Authenticator
 * require browser APIs.
 */
export default function AmplifyProvider({
  children,
}: {
  children: React.ReactNode;
}) {
  const [ready, setReady] = useState(false);

  useEffect(() => {
    // amplify_outputs.json is generated by `npx ampx sandbox` or CI/CD.
    // It is git-ignored and must never be committed.
    import('@/amplify_outputs.json')
      .then(async (outputs) => {
        Amplify.configure(outputs.default, { ssr: true });
        // Eagerly restore the Cognito session from storage so that the token is
        // available before any child page mounts and fires its first data fetch.
        // Swallow errors — a missing session just means the user isn't signed in
        // yet; AuthProvider will show the login modal.
        try { await fetchAuthSession(); } catch { /* not signed in */ }
      })
      .catch(() => {
        console.warn(
          '[Amplify] amplify_outputs.json not found. Run `npx ampx sandbox` to generate it.'
        );
      })
      .finally(() => setReady(true));
  }, []);

  if (!ready) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-gray-400 text-sm">Loading…</div>
      </div>
    );
  }

  return <Authenticator.Provider>{children}</Authenticator.Provider>;
}
